# Generated by Django 4.2 on 2023-04-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=8)),
                ('state_or_district', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=4)),
                ('phone_number1', models.CharField(max_length=10)),
                ('phone_number2', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
